// Unit tests for Going, Going, GONE!'s lot data and draw — `npm run test:unit`, no browser.
//
// The lots are REAL items with researched prices, and the JSON files are the source of truth;
// goinggone.html carries an embedded copy generated by scripts/build-goinggone-lots.js. The most
// valuable test here is the first one: it fails when somebody edits the JSON and forgets to
// regenerate, which would otherwise show up as a wrong price mid-game with no error anywhere.
//
// The second most valuable is the BAND DEPTH suite. Lots are dealt evenly across four price
// bands, so a band with too few researched lots silently starts repeating items within a single
// auction. That is a research gap, not a code bug, and this is where it surfaces.
const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const HTML = fs.readFileSync(path.join(ROOT, 'goinggone.html'), 'utf8');

// ── pull the embedded lots and the draw out of the page ─────────────────────
const LOTS = new Function(HTML.match(/const LOTS = \[[\s\S]*?\n\];/)[0] + '\nreturn LOTS;')();

const DRAW_SRC = (() => {
    const a = HTML.indexOf('const BANDS = [');
    const b = HTML.indexOf('function hostStartAuction', a);
    assert.ok(a >= 0 && b > a, 'could not slice the lot-draw block out of goinggone.html');
    return HTML.slice(a, b);
})();

// Evaluate the draw with its collaborators passed in as parameters, so nothing touches globals.
const makeDraw = (settings, players = 6) => {
    const shuffle = a => a.slice();                     // deterministic: identity shuffle
    const H = { settings, mysteryLots: null };
    const fn = new Function('LOTS', 'shuffle', 'H', 'MIN_PLAYERS', 'connectedPlayers',
        DRAW_SRC + '\nreturn { buildLotOrder, plannedLotCount, BANDS, OVER_BAND, MYSTERY_SHARE, H };');
    return fn(LOTS, shuffle, H, 2, () => Array.from({ length: players }));
};

const SOURCES = ['data/goinggone-lots-real.json', 'data/goinggone-lots-catalogue.json'];
const jsonLots = SOURCES
    .flatMap(f => JSON.parse(fs.readFileSync(path.join(ROOT, f), 'utf8')).lots)
    .filter(l => Math.round(l.value) > 0);

// ── the embed matches its source ────────────────────────────────────────────
test('embedded LOTS matches the JSON sources — run scripts/build-goinggone-lots.js if this fails', () => {
    assert.equal(LOTS.length, jsonLots.length,
        `embed has ${LOTS.length} lots, JSON has ${jsonLots.length} — the embed is stale`);
    jsonLots.forEach((src, i) => {
        assert.equal(LOTS[i].name, src.name, `lot ${i} name drifted from the JSON`);
        assert.equal(LOTS[i].value, Math.round(src.value), `lot ${i} (${src.name}) value drifted`);
    });
});

test('every value is a positive whole number of dollars', () => {
    // The game's coin arithmetic is integer and bidding in cents is silly, so the build script
    // rounds. A stray float here would show up as $4084.85 on a lot card.
    for (const l of LOTS) {
        assert.ok(Number.isInteger(l.value), `${l.name} has a non-integer value ${l.value}`);
        assert.ok(l.value > 0, `${l.name} is worth ${l.value} — nothing free or negative`);
    }
});

test('every lot carries the provenance shown while bidding', () => {
    // src + capture date are rendered on the lot card on purpose: real prices move, and a
    // figure that looks wrong needs a visible explanation rather than looking like a bug.
    for (const l of LOTS) {
        assert.ok(l.src && l.src.length, `${l.name} has no source label`);
        assert.match(l.on || '', /^\d{4}-\d{2}-\d{2}$/, `${l.name} has no capture date`);
    }
});

// ── no lot may reveal its own price ─────────────────────────────────────────
// The whole game is guessing what the thing costs. The catalogue harvest wrote the price into
// the flavour text ("A lump of iron with a handle. Thirty-eight dollars.") — 57 lots leaked
// their own answer onto the bidding screen before this test existed. Checks the JSON sources,
// not the embed, so the failure names the file to fix.
const NUM_WORD = '(?:one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|' +
    'fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty|sixty|' +
    'seventy|eighty|ninety|hundred|thousand|million)';
const PRICE_LEAKS = [
    /\$\s*\d/,                                      // "$799"
    /\b(?:dollars?|bucks|quid)\b/i,                 // "…dollars." spelled out or not
    new RegExp('\\b(?:' + NUM_WORD + '|\\d+)[\\s-]*grand\\b', 'i'),  // "four grand", "10 grand"
];
test('no lot name or description states its own price', () => {
    const leaks = [];
    for (const f of SOURCES) {
        for (const l of JSON.parse(fs.readFileSync(path.join(ROOT, f), 'utf8')).lots) {
            for (const field of ['name', 'desc']) {
                const hit = PRICE_LEAKS.find(re => re.test(l[field] || ''));
                if (hit) leaks.push(`${f}: "${l.name}" ${field} leaks the price (${hit}): ${l[field]}`);
            }
        }
    }
    assert.deepEqual(leaks, [],
        `${leaks.length} lot(s) reveal their price on the bidding screen:\n  ` + leaks.join('\n  '));
});

// ── band depth: a research check, not a code check ──────────────────────────
test('every price band can fill the largest possible auction without repeating', () => {
    const { BANDS } = makeDraw({ lotsPer: 3, bigLot: false });
    const MAX_DRAW = 10 * 4;                             // MAX_PLAYERS x the longest setting
    const perBand = Math.ceil(MAX_DRAW / BANDS.length);
    const report = [];
    for (const [lo, hi] of BANDS) {
        const n = LOTS.filter(l => l.value >= lo && l.value < hi).length;
        report.push(`$${lo}-${hi}: ${n} (needs ${perBand})`);
        assert.ok(n >= perBand,
            `band $${lo}-${hi} has only ${n} lots but a full table draws ${perBand} — ` +
            `research more lots in this band or the same item appears twice in one auction`);
    }
    console.log('      band depth →', report.join(', '));
});

// ── the draw ────────────────────────────────────────────────────────────────
test('buildLotOrder returns the requested number of DISTINCT lots', () => {
    const { buildLotOrder } = makeDraw({ lotsPer: 3, bigLot: false });
    for (const count of [6, 12, 18, 30, 40]) {
        const order = buildLotOrder(count);
        assert.equal(order.length, count, `asked for ${count} lots, got ${order.length}`);
        assert.equal(new Set(order).size, count, `count ${count} repeated a lot within one auction`);
    }
});

test('the draw spreads evenly across the bands', () => {
    // This is what makes a short auction still span $1 to $10,000 instead of clumping, and it is
    // the assumption every balance figure in goinggoneplan-realitems.md rests on.
    const { buildLotOrder, BANDS } = makeDraw({ lotsPer: 3, bigLot: false });
    const order = buildLotOrder(20);
    const counts = BANDS.map(([lo, hi]) => order.filter(i => LOTS[i].value >= lo && LOTS[i].value < hi).length);
    assert.deepEqual(counts, [5, 5, 5, 5], `expected an even spread, got ${counts.join('/')}`);
});

test('over-band lots stay out unless the captain asks for one', () => {
    // The simulator is unambiguous: one lot worth more than the whole ordinary band takes the
    // winner's margin from ~10% of their score to ~48%, i.e. it decides the game by itself.
    const off = makeDraw({ lotsPer: 3, bigLot: false });
    const offOrder = off.buildLotOrder(18);
    assert.equal(offOrder.filter(i => LOTS[i].value >= off.OVER_BAND).length, 0,
        'a big lot appeared with the setting off — that silently changes the balance of every game');

    const on = makeDraw({ lotsPer: 3, bigLot: true });
    const onOrder = on.buildLotOrder(18);
    assert.equal(onOrder.filter(i => LOTS[i].value >= on.OVER_BAND).length, 1,
        'bigLot should add exactly one over-band lot, never more');
});

test('mystery lots always have a photo, because the photo is all you get', () => {
    // A mystery lot withholds the name and shows the picture. One without a picture would be a
    // blank card nobody can bid on sensibly.
    const draw = makeDraw({ lotsPer: 3, bigLot: false });
    const order = draw.buildLotOrder(20);
    const mystery = [...draw.H.mysteryLots];
    assert.ok(mystery.length > 0, 'no mystery lots were chosen at all');
    assert.equal(mystery.length, Math.round(order.length * draw.MYSTERY_SHARE));
    for (const i of mystery) {
        assert.ok(LOTS[i].img, `${LOTS[i].name} was made a mystery lot but has no photo`);
        assert.ok(order.includes(i), 'a mystery lot was chosen that is not even in this auction');
    }
});

test('lot count scales with the table, ~3 per player', () => {
    // "Everyone goes home with about three things" should hold at any table size.
    for (const players of [2, 4, 6, 10]) {
        const { plannedLotCount } = makeDraw({ lotsPer: 3, bigLot: false }, players);
        assert.equal(plannedLotCount(), players * 3, `${players} players should draw ${players * 3} lots`);
    }
    const { plannedLotCount } = makeDraw({ lotsPer: 2, bigLot: false }, 6);
    assert.equal(plannedLotCount(), 12, 'the Short setting should be 2 lots per player');
});
