// Unit tests for Going, Going, GONE!'s lot data and draw — `npm run test:unit`, no browser.
//
// The lots are REAL items with researched prices, and the JSON files are the source of truth;
// goinggone.html carries an embedded copy generated by scripts/build-goinggone-lots.js. The most
// valuable test here is the first one: it fails when somebody edits the JSON and forgets to
// regenerate, which would otherwise show up as a wrong price mid-game with no error anywhere.
//
// The second most valuable is the BAND DEPTH suite. Lots are dealt evenly across four price
// bands, so a band with too few researched lots silently starts repeating items within a single
// auction. That is a research gap, not a code bug, and this is where it surfaces.
const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const HTML = fs.readFileSync(path.join(ROOT, 'goinggone.html'), 'utf8');

// ── pull the embedded lots and the draw out of the page ─────────────────────
const LOTS = new Function(HTML.match(/const LOTS = \[[\s\S]*?\n\];/)[0] + '\nreturn LOTS;')();

const DRAW_SRC = (() => {
    const a = HTML.indexOf('const TIERS = [');
    const b = HTML.indexOf('function hostStartAuction', a);
    assert.ok(a >= 0 && b > a, 'could not slice the lot-draw block out of goinggone.html');
    return HTML.slice(a, b);
})();

// The auctioneer's ask ladder + reserve live up with the raise ladder, not with the draw.
const ASK_SRC = (() => {
    const a = HTML.indexOf('const RESERVE_FRAC =');
    const b = HTML.indexOf('const PLAYER_COLORS', a);
    assert.ok(a >= 0 && b > a, 'could not slice the ask-ladder block out of goinggone.html');
    return HTML.slice(a, b);
})();

// Evaluate the draw with its collaborators passed in as parameters, so nothing touches globals.
// `ceiling` is the richest bankroll — Infinity in most tests, where affordability is not the point.
const makeDraw = (settings, players = 6) => {
    const shuffle = a => a.slice();                     // deterministic: identity shuffle
    const H = { settings, mysteryLots: null, usedLots: null };
    const fn = new Function('LOTS', 'shuffle', 'H', 'MIN_PLAYERS', 'connectedPlayers', 'reserveFor',
        DRAW_SRC + '\nreturn { buildLotOrder, plannedLotCount, roundBands, TIERS, BAND_SPAN, OVER_BAND, REACH, MYSTERY_SHARE, H };');
    const d = fn(LOTS, shuffle, H, 2, () => Array.from({ length: players }), v => Math.round(v * 0.25));
    // most tests predate rounds and just want "one round, everything affordable"
    const raw = d.buildLotOrder;
    d.buildLotOrder = (n, round = 1, rounds = 1, ceiling = Infinity) => raw(n, round, rounds, ceiling);
    d.rawBuildLotOrder = raw;
    return d;
};

const ASK = new Function(ASK_SRC + '\nreturn { askLadder, reserveFor, roundAsk, RESERVE_FRAC, ASK_HI, ASK_LO, ASK_STEPS };')();

// The raise ladder and the increment-splitting that softens it as the gavel falls.
const RAISE_SRC = (() => {
    const a = HTML.indexOf('const RAISE_LADDER = [');
    const b = HTML.indexOf('const PLAYER_COLORS', a);
    assert.ok(a >= 0 && b > a, 'could not slice the raise-ladder block out of goinggone.html');
    return HTML.slice(a, b);
})();
const RAISE = new Function(RAISE_SRC +
    '\nreturn { raisesFor, softMinRaise, askLadderFor, lastRung, RAISE_FLOOR, SOFT_SHARE, SOFT_STEPS };')();

// THE CLOCK. Every number that decides how long a player has to think, in one block, so the rules
// document (goinggone-rules.md), the game and these tests cannot drift apart.
const CLOCK_SRC = (() => {
    const a = HTML.indexOf('const MIN_DECIDE_MS =');
    const b = HTML.indexOf('const CLOSE_BEATS', a);
    assert.ok(a >= 0 && b > a, 'could not slice the clock block out of goinggone.html');
    return HTML.slice(a, HTML.indexOf(';', b) + 1);
})();
const CLOCK = new Function(CLOCK_SRC + '\nreturn { MIN_DECIDE_MS, INTRO_MS, SOLD_MS, PASSED_MS, REVEAL_MS,' +
    ' ASK_WINDOWS, GAVEL_MS, SOFT_WINDOWS, CLOSE_BEAT_MS, CLOSE_BEATS };')();

// What the room is allowed to learn about everybody else's purse.
const PURSE_SRC = (() => {
    const a = HTML.indexOf('const PURSE_HIDDEN = [');
    const b = HTML.indexOf('function stateFor', a);
    assert.ok(a >= 0 && b > a, 'could not slice the purse-band block out of goinggone.html');
    return HTML.slice(a, b);
})();
const PURSE = new Function(PURSE_SRC + '\nreturn { purseBand, PURSE_BANDS, PURSE_HIDDEN };')();

// Which voice calls the auction.
const VOICE_SRC = (() => {
    const a = HTML.indexOf('const VOICE_PREF = [');
    const b = HTML.indexOf('function shutUp', a);
    assert.ok(a >= 0 && b > a, 'could not slice the voice-ranking block out of goinggone.html');
    return HTML.slice(a, b);
})();
const VOICE = new Function(VOICE_SRC + '\nreturn { voiceScore, VOICE_PREF };')();
const best = list => list.slice().sort((x, y) => VOICE.voiceScore(y) - VOICE.voiceScore(x))[0].name;

// The auctioneer speaks his numbers, so they have to be built into words rather than left to a
// speech engine to spell out digit by digit.
const SPEAK_SRC = (() => {
    const a = HTML.indexOf('const ONES = [');
    const b = HTML.indexOf('const pick = ', a);
    assert.ok(a >= 0 && b > a, 'could not slice the number-to-words block out of goinggone.html');
    return HTML.slice(a, b);
})();
const { words } = new Function(SPEAK_SRC + '\nreturn { words };')();

const SOURCES = ['data/goinggone-lots-real.json', 'data/goinggone-lots-catalogue.json'];
const jsonLots = SOURCES
    .flatMap(f => JSON.parse(fs.readFileSync(path.join(ROOT, f), 'utf8')).lots)
    .filter(l => Math.round(l.value) > 0);

// ── the embed matches its source ────────────────────────────────────────────
test('embedded LOTS matches the JSON sources — run scripts/build-goinggone-lots.js if this fails', () => {
    assert.equal(LOTS.length, jsonLots.length,
        `embed has ${LOTS.length} lots, JSON has ${jsonLots.length} — the embed is stale`);
    jsonLots.forEach((src, i) => {
        assert.equal(LOTS[i].name, src.name, `lot ${i} name drifted from the JSON`);
        assert.equal(LOTS[i].value, Math.round(src.value), `lot ${i} (${src.name}) value drifted`);
    });
});

test('every value is a positive whole number of dollars', () => {
    // The game's coin arithmetic is integer and bidding in cents is silly, so the build script
    // rounds. A stray float here would show up as $4084.85 on a lot card.
    for (const l of LOTS) {
        assert.ok(Number.isInteger(l.value), `${l.name} has a non-integer value ${l.value}`);
        assert.ok(l.value > 0, `${l.name} is worth ${l.value} — nothing free or negative`);
    }
});

test('every lot carries the provenance shown while bidding', () => {
    // src + capture date are rendered on the lot card on purpose: real prices move, and a
    // figure that looks wrong needs a visible explanation rather than looking like a bug.
    for (const l of LOTS) {
        assert.ok(l.src && l.src.length, `${l.name} has no source label`);
        assert.match(l.on || '', /^\d{4}-\d{2}-\d{2}$/, `${l.name} has no capture date`);
    }
});

// ── no lot may reveal its own price ─────────────────────────────────────────
// The whole game is guessing what the thing costs. The catalogue harvest wrote the price into
// the flavour text ("A lump of iron with a handle. Thirty-eight dollars.") — 57 lots leaked
// their own answer onto the bidding screen before this test existed. Checks the JSON sources,
// not the embed, so the failure names the file to fix.
const NUM_WORD = '(?:one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|' +
    'fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty|sixty|' +
    'seventy|eighty|ninety|hundred|thousand|million)';
const PRICE_LEAKS = [
    /\$\s*\d/,                                      // "$799"
    /\b(?:dollars?|cents?|bucks|quid)\b/i,          // "…dollars." / "Fifty cents." spelled out or not
    new RegExp('\\b(?:' + NUM_WORD + '|\\d+)[\\s-]*grand\\b', 'i'),  // "four grand", "10 grand"
    // Comparative hints are banned too — "costs more than a car", "the most expensive harp
    // there is", "twice the price". Fuzzier than a number, but still the auctioneer whispering
    // the answer. Any price-adjacent word fails; reword the joke around it.
    /\b(?:price[sdy]?|priciest|cost(?:s|ing|ly)?|cheap(?:er|est)?|expensive|afford(?:able)?|bargain|fortune|worth)\b/i,
];
test('no lot name or description states its own price', () => {
    const leaks = [];
    for (const f of SOURCES) {
        for (const l of JSON.parse(fs.readFileSync(path.join(ROOT, f), 'utf8')).lots) {
            for (const field of ['name', 'desc']) {
                const hit = PRICE_LEAKS.find(re => re.test(l[field] || ''));
                if (hit) leaks.push(`${f}: "${l.name}" ${field} leaks the price (${hit}): ${l[field]}`);
            }
        }
    }
    assert.deepEqual(leaks, [],
        `${leaks.length} lot(s) reveal their price on the bidding screen:\n  ` + leaks.join('\n  '));
});

// ── band depth: a research check, not a code check ──────────────────────────
// Repeats are impossible by construction now (H.usedLots excludes everything already dealt, in
// this round and every earlier one), so a thin tier no longer shows the same item twice. What it
// does instead is quietly under-represent itself: the draw rotates on to the next tier and the
// round loses the price range it was supposed to span. So the hard floor is "deep enough for an
// ordinary table", and anything thinner than the largest possible draw is REPORTED as a research
// target rather than failed — the top tier is only ever reached in the last round of a 3-round
// game, and holding the whole suite red over it would be dishonest about the severity.
test('every price tier is deep enough for an ordinary table', () => {
    const { TIERS, BAND_SPAN } = makeDraw({ lotsPer: 3, bigLot: false });
    const TYPICAL = 6 * 3;                               // 6 players, the Normal setting
    const MAX_DRAW = 10 * 4;                             // MAX_PLAYERS x the longest setting
    const floor = Math.ceil(TYPICAL / BAND_SPAN);
    const want = Math.ceil(MAX_DRAW / BAND_SPAN);
    const report = [], thin = [];
    for (const [lo, hi] of TIERS) {
        const n = LOTS.filter(l => l.value >= lo && l.value < hi).length;
        report.push(`$${lo}-${hi}: ${n}`);
        if (n < want) thin.push(`$${lo}-${hi} has ${n}, wants ${want} for the biggest table`);
        assert.ok(n >= floor,
            `tier $${lo}-${hi} has only ${n} lots and an ordinary table draws ${floor} — ` +
            `research more lots in this tier or a round stops spanning its price range`);
    }
    console.log('      tier depth →', report.join(', '));
    if (thin.length) console.log('      RESEARCH TARGETS →', thin.join('; '));
});

// ── the draw ────────────────────────────────────────────────────────────────
test('buildLotOrder returns the requested number of DISTINCT lots', () => {
    const { buildLotOrder } = makeDraw({ lotsPer: 3, bigLot: false });
    for (const count of [6, 12, 18, 30, 40]) {
        const order = buildLotOrder(count);
        assert.equal(order.length, count, `asked for ${count} lots, got ${order.length}`);
        assert.equal(new Set(order).size, count, `count ${count} repeated a lot within one auction`);
    }
});

test('the draw spreads evenly across the bands', () => {
    // This is what makes a short auction still span $1 to $10,000 instead of clumping, and it is
    // the assumption every balance figure in goinggoneplan-realitems.md rests on.
    const { buildLotOrder, roundBands } = makeDraw({ lotsPer: 3, bigLot: false });
    const order = buildLotOrder(20);
    const counts = roundBands(1, 1).map(([lo, hi]) => order.filter(i => LOTS[i].value >= lo && LOTS[i].value < hi).length);
    assert.deepEqual(counts, [5, 5, 5, 5], `expected an even spread, got ${counts.join('/')}`);
});

test('over-band lots stay out unless the captain asks for one', () => {
    // The simulator is unambiguous: one lot worth more than the whole ordinary band takes the
    // winner's margin from ~10% of their score to ~48%, i.e. it decides the game by itself.
    const off = makeDraw({ lotsPer: 3, bigLot: false });
    const offOrder = off.buildLotOrder(18);
    assert.equal(offOrder.filter(i => LOTS[i].value >= off.OVER_BAND).length, 0,
        'a big lot appeared with the setting off — that silently changes the balance of every game');

    const on = makeDraw({ lotsPer: 3, bigLot: true });
    const onOrder = on.buildLotOrder(18);
    assert.equal(onOrder.filter(i => LOTS[i].value >= on.OVER_BAND).length, 1,
        'bigLot should add exactly one over-band lot, never more');
});

test('mystery lots always have a photo, because the photo is all you get', () => {
    // A mystery lot withholds the name and shows the picture. One without a picture would be a
    // blank card nobody can bid on sensibly.
    const draw = makeDraw({ lotsPer: 3, bigLot: false });
    const order = draw.buildLotOrder(20);
    const mystery = [...draw.H.mysteryLots];
    assert.ok(mystery.length > 0, 'no mystery lots were chosen at all');
    assert.equal(mystery.length, Math.round(order.length * draw.MYSTERY_SHARE));
    for (const i of mystery) {
        assert.ok(LOTS[i].img, `${LOTS[i].name} was made a mystery lot but has no photo`);
        assert.ok(order.includes(i), 'a mystery lot was chosen that is not even in this auction');
    }
});

// ── rounds: the bands climb, and nothing is ever sold twice ─────────────────
test('the band window climbs with the round and always tops out in the last one', () => {
    const { roundBands, TIERS, BAND_SPAN } = makeDraw({ lotsPer: 3, bigLot: false });
    // one round: the ordinary spread, never the monsters
    assert.deepEqual(roundBands(1, 1), TIERS.slice(0, BAND_SPAN));
    // three rounds: opens ordinary, ends at the top of the ladder
    assert.deepEqual(roundBands(1, 3), TIERS.slice(0, BAND_SPAN));
    assert.deepEqual(roundBands(3, 3), TIERS.slice(-BAND_SPAN));
    // two rounds must ALSO reach the top by the end — a shorter game should not be capped out of
    // the private-aircraft tier just for being shorter
    assert.deepEqual(roundBands(2, 2), TIERS.slice(-BAND_SPAN));
    // and the window never falls off the end of the ladder
    for (const rounds of [1, 2, 3]) {
        for (let r = 1; r <= rounds; r++) {
            assert.equal(roundBands(r, rounds).length, BAND_SPAN, `round ${r}/${rounds} lost a tier`);
        }
    }
});

test('a multi-round game never sells the same item twice', () => {
    // H.usedLots spans the whole game, not the round. Without it round 3 can re-deal round 1's
    // lot — and a player who watched it get valued knows exactly what it is worth.
    const draw = makeDraw({ lotsPer: 3, bigLot: false });
    const seen = new Set();
    for (let round = 1; round <= 3; round++) {
        const order = draw.buildLotOrder(18, round, 3, Infinity);
        for (const i of order) {
            assert.ok(!seen.has(i), `${LOTS[i].name} was dealt twice in one game (round ${round})`);
            seen.add(i);
        }
    }
});

test('a lot nobody could clear the reserve on never reaches the running order', () => {
    // Affordability is judged lot by lot: a $70,000 oven in front of a table holding $9,000 is a
    // pass-in nobody enjoyed. REACH is how much of the richest bankroll a reserve may demand.
    const draw = makeDraw({ lotsPer: 3, bigLot: false });
    const ceiling = 9000;
    const order = draw.buildLotOrder(18, 3, 3, ceiling);
    for (const i of order) {
        assert.ok(ASK.reserveFor(LOTS[i].value) <= ceiling * draw.REACH,
            `${LOTS[i].name} ($${LOTS[i].value}) was dealt to a table whose richest player holds $${ceiling}`);
    }
});

// ── the auctioneer's ask ────────────────────────────────────────────────────
test('the ask ladder descends, and never goes under the reserve', () => {
    // The floor is the whole point: below it the lot is passed in rather than given away.
    for (const value of [1, 15, 99, 450, 2200, 9500, 19799, 70886]) {
        for (let n = 0; n < 200; n++) {
            const ladder = ASK.askLadder(value);
            assert.ok(ladder.length >= 1 && ladder.length <= ASK.ASK_STEPS, `${value}: ${ladder.length} rungs`);
            ladder.forEach((a, i) => {
                assert.ok(a >= ASK.reserveFor(value) || a >= value * ASK.RESERVE_FRAC,
                    `${value}: rung ${a} is under the reserve ${ASK.reserveFor(value)}`);
                assert.ok(a >= 1, `${value}: rung ${a} is not a price`);
                if (i) assert.ok(a < ladder[i - 1], `${value}: ladder went UP (${ladder.join(' → ')})`);
            });
            // +1 of slack: rounding a $1 tulip bulb to a callable number can only go up
            assert.ok(ladder[0] <= Math.max(1, value * ASK.ASK_HI) * 1.05 + 1,
                `${value}: opening ask ${ladder[0]} is beyond even a dishonest auctioneer`);
        }
    }
});

test('the opening ask is sometimes a gift and sometimes a swindle', () => {
    // If he always asked above the value the room would learn to wait every time, and if he always
    // asked below it there would be no risk in jumping early. Both sides must actually occur.
    const value = 4000;
    let over = 0, under = 0;
    for (let n = 0; n < 400; n++) {
        const open = ASK.askLadder(value)[0];
        if (open > value) over++; else under++;
    }
    assert.ok(over > 20 && under > 20, `openings were one-sided: ${over} over / ${under} under`);
});

test('asks are round numbers a person would say out loud', () => {
    // "Who will start me at forty-seven thousand three hundred and eighteen?" — no.
    for (const v of [850, 4200, 19799, 70886]) {
        for (const a of ASK.askLadder(v)) {
            const digits = String(a).replace(/0+$/, '').length;
            assert.ok(a < 20 || digits <= 2, `${a} is not a number an auctioneer would call`);
        }
    }
});

// ── THE CLOCK ───────────────────────────────────────────────────────────────────────────────
// A window is a decision. Too short and it is a reflex test; too long and the room goes flat and
// people stop watching. These are the guarantees the rules document makes to a player.

test('no decision window is ever shorter than a person can decide in', () => {
    const every = [...CLOCK.ASK_WINDOWS, CLOCK.GAVEL_MS, ...CLOCK.SOFT_WINDOWS];
    for (const ms of every) {
        assert.ok(ms >= CLOCK.MIN_DECIDE_MS, `${ms}ms is under the ${CLOCK.MIN_DECIDE_MS}ms floor`);
    }
});

test('a bid always buys the longest window on the board', () => {
    // Whatever pressure he had built, a bid resets the clock in full. Otherwise the player who
    // just committed money is punished with less time than the one who sat still.
    const other = [...CLOCK.ASK_WINDOWS.slice(1), ...CLOCK.SOFT_WINDOWS, CLOCK.CLOSE_BEAT_MS];
    for (const ms of other) assert.ok(CLOCK.GAVEL_MS >= ms, `a bid buys ${CLOCK.GAVEL_MS}ms, but some beat runs ${ms}ms`);
});

test('he speeds up as the room stays silent — never slows down', () => {
    // The whole feel of the fishing phase is impatience. Each unanswered ask must come quicker
    // than the last, all the way down to the floor.
    for (let i = 1; i < CLOCK.ASK_WINDOWS.length; i++) {
        assert.ok(CLOCK.ASK_WINDOWS[i] < CLOCK.ASK_WINDOWS[i - 1],
            `ask window ${i} (${CLOCK.ASK_WINDOWS[i]}ms) is not quicker than the one before it`);
    }
    for (let i = 1; i < CLOCK.SOFT_WINDOWS.length; i++) {
        assert.ok(CLOCK.SOFT_WINDOWS[i] < CLOCK.SOFT_WINDOWS[i - 1],
            `reduced ask ${i} (${CLOCK.SOFT_WINDOWS[i]}ms) is not quicker than the one before it`);
    }
});

test('the close is short, and it is two beats', () => {
    // "Going once, going twice" is the bit everyone knows. It only lands if it is quick and if
    // both halves are actually said — one long window with a changing caption is not the same
    // thing. Bids are still legal here, which is what makes it a snipe window rather than a wait.
    assert.equal(CLOCK.CLOSE_BEATS, 2, 'once and twice: two beats, no more, no fewer');
    assert.ok(CLOCK.CLOSE_BEAT_MS <= 2000, 'a slow close is a dead close');
    assert.ok(CLOCK.CLOSE_BEAT_MS >= 1200, 'under 1.2s nobody can snipe it, and nobody hears the line');
});

test('the dullest outcome is never the longest to sit through', () => {
    // A lot nobody wants used to take 38 seconds — longer than one that sold. That is exactly
    // backwards: a dead lot should be got rid of, not endured.
    const passedIn = CLOCK.INTRO_MS + CLOCK.ASK_WINDOWS.reduce((a, b) => a + b, 0) + CLOCK.PASSED_MS;
    const oneBid = CLOCK.INTRO_MS + CLOCK.ASK_WINDOWS[0] + CLOCK.GAVEL_MS +
        CLOCK.SOFT_WINDOWS.reduce((a, b) => a + b, 0) + CLOCK.CLOSE_BEATS * CLOCK.CLOSE_BEAT_MS + CLOCK.SOLD_MS;
    assert.ok(passedIn <= oneBid, `a pass-in takes ${passedIn}ms but a sale takes only ${oneBid}ms`);
    assert.ok(passedIn <= 30000, `${Math.round(passedIn / 1000)}s of nothing happening is too long`);
});

test('the descent is not one gavel long', () => {
    // The descent used to be derived from how much of a single five-second gavel had elapsed,
    // which left the cheapest ask on offer for well under a second — a reflex test, not a
    // decision. Each step now has its own window.
    const total = CLOCK.SOFT_WINDOWS.reduce((a, b) => a + b, 0);
    assert.ok(total >= 8000, `the whole descent lasts only ${total}ms`);
});

test('the host has exactly one place that decides how long a beat lasts', () => {
    // windowFor() is what the rules document describes. If a branch ever sets endsAt by hand
    // again the documented table stops being true, so the game must go through openWindow().
    assert.ok(/function windowFor\(/.test(HTML), 'windowFor() is the single source of the schedule');
    const src = HTML.slice(HTML.indexOf('function startBidding'), HTML.indexOf('function startValuation'))
        .replace(/function openWindow\([\s\S]*?\n\}/, '');   // …which is the one place allowed to set it
    const hand = [...src.matchAll(/H\.bid\.endsAt\s*=/g)].length;
    assert.equal(hand, 0, 'a beat sets H.bid.endsAt directly instead of calling openWindow()');
});

test('the close never talks over itself', () => {
    // Both clients suppress the "going…" escalation while closing — otherwise the fair-warning
    // chant fires on top of "GOING ONCE" and the two lines cancel each other in speechSynthesis.
    const ticks = [...HTML.matchAll(/const stage = \(_[cv]Opening \|\| ([^)]*)\)/g)].map(m => m[1]);
    assert.equal(ticks.length, 2, 'both the phone and the TV countdowns must be found');
    for (const cond of ticks) assert.ok(/closing/.test(cond), `the close is not suppressing "going…": ${cond}`);
});

test('nothing decorative is allowed to swallow the hammer', () => {
    // The TV called the sale from inside a setTimeout that ran the confetti FIRST. One throw
    // anywhere in the particle code and the lot ends with no voice at all — which is a mystery
    // from a sofa, and was a one-in-three flake in the auction e2e. The call comes first.
    for (const [start, end, who] of [['function applyMsg', 'function startClientGavel', 'the phone'],
                                     ['function applyViewerMsg', 'function startViewerGavel', 'the TV']]) {
        const src = HTML.slice(HTML.indexOf(start), HTML.indexOf(end));
        const sold = src.slice(src.indexOf("phase === 'sold'"), src.indexOf("phase === 'valuation'"));
        // lastIndexOf, not indexOf: the passed-in case calls saySold first and would mask a sold
        // case that had been ordered the wrong way round.
        const call = sold.lastIndexOf('saySold(');
        const fx = sold.lastIndexOf('burst(');
        assert.ok(call >= 0, `${who} never calls the sale`);
        if (fx >= 0) assert.ok(call < fx, `${who} runs its confetti before calling the sale`);
    }
});

test('no window is ever silent — he re-asks partway through', () => {
    // Real auctioneers never stop firing: "Will you go six? Will you give six? Will you buy 'em
    // at six?" A quiet five seconds reads as a frozen screen, not as suspense.
    assert.ok(/const P_CHANT = \[/.test(HTML), 'there is no mid-window chant');
    assert.equal([...HTML.matchAll(/sayChant\(/g)].length, 3, 'the chant must fire on the phone and the TV (and be defined once)');
});

test('he says one line aloud and shows the rest', () => {
    // Spoken numbers are dear — "forty-five thousand nine hundred" is three seconds — so the
    // banked board would have to be held open for eighteen seconds to let two lines finish, and
    // a TV with no voice would sit on a silent screen for all of it. Neil heard the round-end
    // commentary cut off mid-sentence when the board moved on beneath it.
    const SRC = HTML.slice(HTML.indexOf('const SPOKEN_COMMENTARY'), HTML.indexOf('const fill ='));
    const n = +(/const SPOKEN_COMMENTARY = (\d+)/.exec(SRC) || [])[1];
    assert.equal(n, 1, 'more than one spoken line pushes the banked hold past what it is worth');

    // and the board must wait for however long he actually needs
    const bank = HTML.slice(HTML.indexOf('function startBanking'), HTML.indexOf('function hostNewGame'));
    assert.match(bank, /speechMs\(/, 'the banked hold must be measured against the speech, not fixed');
    assert.match(bank, /Math\.max\(/, 'and never shorter than the rows take to land');
});

test('when he splits the increment he calls the PRICE, not the step', () => {
    // Heard in a real game: bid at 140, ask reduced to 25, and he said "I'll take 25". An
    // auctioneer never calls the increment — he calls the price it makes, "one hundred and
    // sixty-five". The increment is only ever spoken as "just X more".
    // to the array's own closing bracket, NOT to the next const: the comment in between quotes
    // "{who}", which this happily read as a line of patter
    const from = HTML.indexOf('const P_SPLIT = [');
    const SRC = HTML.slice(from, HTML.indexOf('];', from));
    const lines = [...SRC.matchAll(/"((?:\\.|[^"])*)"/g)].map(m => m[1]);
    assert.ok(lines.length >= 5, `only ${lines.length} split lines found`);
    for (const l of lines) {
        assert.match(l, /\{n\}/, `"${l}" never names the price the ask would make`);
        // {r} is allowed, but only where "more" makes it obviously an increment
        if (/\{r\}/.test(l)) {
            assert.match(l, /\{r\}\s*(more|\.|!|\?)/,
                `"${l}" uses the increment somewhere it will be heard as a price`);
        }
    }

    // …and no trade jargon: a family is not an auction house
    const JARGON = /split it with me|bid'em|chandelier|on the book/i;
    for (const l of lines) assert.ok(!JARGON.test(l), `"${l}" is shop-talk nobody at a table will follow`);

    // and the substitution feeds them the right numbers. Matched as RAW text: in the source the
    // placeholders live inside a regex literal, so "{n}" is written `\{n\}` and a plain /\{n\}/
    // never finds it — the backslash sits between the n and the brace.
    const say = HTML.slice(HTML.indexOf('function saySplit'), HTML.indexOf('function sayChant'));
    assert.ok(say.includes(String.raw`.replace(/\{n\}/g, words(price + minRaise))`),
        '{n} must be substituted with the price the ask would make');
    assert.ok(say.includes(String.raw`.replace(/\{r\}/g, words(minRaise))`),
        '{r} must be substituted with the increment');
});

// ── nobody may read your bank balance off the TV ────────────────────────────
test('the purse band never rises as you get poorer', () => {
    const avg = 7000;
    let prev = null;
    const order = ['flush', 'comfortable', 'short', 'skint'];
    for (const coins of [40000, 20000, 10500, 9000, 7000, 5600, 3000, 2100, 1000, 100, 0]) {
        const band = PURSE.purseBand(coins, avg);
        assert.ok(order.includes(band), `${coins} produced "${band}"`);
        if (prev !== null) {
            assert.ok(order.indexOf(band) >= order.indexOf(prev),
                `${coins} reads "${band}" but a richer player read "${prev}"`);
        }
        prev = band;
    }
});

test('a band is a judgement, not the number in disguise', () => {
    // If every purse produced a distinct band it would just be the balance with extra steps.
    // Four bands, and a whole spread of purses has to collapse into each.
    const avg = 7000;
    const bands = [7000, 7200, 6800, 6500, 8000].map(c => PURSE.purseBand(c, avg));
    assert.equal(new Set(bands).size, 1, `similar purses split across bands: ${bands}`);
    assert.equal(PURSE.PURSE_BANDS.length, 4);
});

test('everyone starts the game reading the same', () => {
    // Round one, nobody has spent anything: the room should learn nothing from the rail.
    const equal = [7000, 7000, 7000].map(c => PURSE.purseBand(c, 7000));
    assert.equal(new Set(equal).size, 1, `identical purses read differently: ${equal}`);
});

test('the money is hidden exactly while the bidding is live, and not after', () => {
    // The reveal screens MUST show the numbers — the banked board and the podium are the payoff.
    for (const phase of ['lot_intro', 'bidding', 'sold']) {
        assert.ok(PURSE.PURSE_HIDDEN.includes(phase), `${phase} leaks the purses`);
    }
    for (const phase of ['lobby', 'valuation', 'banked', 'podium']) {
        assert.ok(!PURSE.PURSE_HIDDEN.includes(phase), `${phase} hides money it should be showing`);
    }
});

// ── splitting the increment ─────────────────────────────────────────────────
// An auctioneer who cannot get another full jump asks for less rather than dropping the hammer.
// So the smallest acceptable raise softens as the gavel countdown runs out.
const PRICES = [1, 60, 99, 200, 900, 3400, 9000, 21000, 67000, 153000];

test('the ask only ever comes DOWN as the gavel falls', () => {
    // The floor is a share of the price and the stages are shares of the rung, so on some lots
    // the floor lands above the quarter-rung. Left alone that makes him ask for MORE the more
    // desperate he gets, which is the one thing it must never do.
    for (const p of PRICES) {
        let prev = Infinity;
        for (const step of [0, 1, 2, 3, 4]) {
            const r = RAISE.softMinRaise(p, step);
            assert.ok(r <= prev, `price ${p}: ask went UP at step ${step} (${prev} → ${r})`);
            assert.ok(r >= 1, `price ${p}: ask fell below a pound (${r})`);
            // NB the raise may now EXCEED the nominal rung: he asks for a round PRICE, and
            // reaching one costs whatever it costs.
            prev = r;
        }
    }
});

test('his opening ask is never below a full jump, and every ask is a ROUND price', () => {
    // Heard in a real game: bid at 2,963 and an ask of 3,022. Nobody has ever said that on a
    // rostrum — he asks for three thousand one hundred. So the ladder is built of round prices
    // and the increment is merely what it costs to reach one, which means the raise can be
    // BIGGER than the nominal rung.
    const round = v => v % 25 === 0 || v % 10 === 0 || v % 5 === 0 || v < 100;
    for (const p of PRICES) {
        const first = p + RAISE.softMinRaise(p, 0);
        assert.ok(first >= p + RAISE.raisesFor(p)[0], `price ${p}: opened at ${first}, under a full jump`);
        for (const step of [0, 1, 2, 3]) {
            const ask = p + RAISE.softMinRaise(p, step);
            assert.ok(ask > p, `price ${p} step ${step}: asked ${ask}, at or under the bid`);
            assert.ok(round(ask), `price ${p} step ${step}: ${ask} is not a number anybody would call`);
        }
        assert.ok(RAISE.softMinRaise(p, 3) <= RAISE.softMinRaise(p, 0), `price ${p} never came down`);
    }
});

test('2,963 gets the ladder a real auctioneer would call', () => {
    // Neil's own example, and the shape the whole rewrite exists to produce.
    const asks = [0, 1, 2, 3].map(i => 2963 + RAISE.softMinRaise(2963, i));
    assert.deepEqual(asks, [3250, 3100, 3050, 3000]);
});

test('a cheap lot really does get down to "just one more"', () => {
    // The whole point of the floor being a SHARE of the price: on a traffic cone it reaches $1,
    // and on a Cessna it stops somewhere that is still a bid rather than a reflex test.
    assert.equal(RAISE.softMinRaise(60, RAISE.SOFT_STEPS), 1);
    assert.ok(RAISE.softMinRaise(67000, RAISE.SOFT_STEPS) > 500, 'a five-figure lot should not go to a pound');
    assert.ok(RAISE.softMinRaise(67000, RAISE.SOFT_STEPS) <= 67000 * RAISE.RAISE_FLOOR * 1.2);
});

test('the phone offers ONE option, and it is the auctioneer\'s own number', () => {
    // A rostrum has no menu. Offering his reduced ask alongside two bigger jumps turned the phone
    // into a calculator, and the bigger jumps were exactly the ones nobody was taking — which is
    // why he came down in the first place.
    const src = HTML.slice(HTML.indexOf('function bidBtnsHTML'), HTML.indexOf('function shelfHTML'));
    assert.ok(!/softRaises/.test(src) && !/softRaises/.test(HTML),
        'the phone is still building a menu of raises');
    const buttons = [...src.matchAll(/onclick="sendBid\(/g)].length;
    assert.equal(buttons, 2, 'exactly two bid buttons in the source: the opening ask, and his ask');
    assert.match(src, /softMinRaise\(msg\.bid\.price, msg\.bid\.soft/,
        'the one button must be his CURRENT ask, not a full jump');
});

test('his ask never climbs back up after a bid', () => {
    // He came down because the room would not give him a full jump. A bid at the reduced ask is
    // not evidence they changed their minds, so re-running the whole descent after every single
    // bid is a descent the room has already sat through — measured at seven seconds a lot in
    // sim/goinggone-bidding.js. The gavel still resets in full; the NUMBER does not.
    const src = HTML.slice(HTML.indexOf('function hostBid'), HTML.indexOf('function checkGavel'));
    const raise = src.slice(src.indexOf("can't outbid yourself"));
    assert.ok(!/H\.bid\.soft\s*=\s*0/.test(raise), 'a raise still resets his ask to a full jump');
    assert.match(raise, /openWindow\(GAVEL_MS\)/, 'a bid must still buy back the longest window');
    // …but a brand-new lot does start him at the top again: the sim is unambiguous that carrying
    // a soft rung ACROSS lots nearly doubles the taps, because the price then climbs in dribs.
    const start = HTML.slice(HTML.indexOf('function startBidding'), HTML.indexOf('const currentAsk'));
    assert.match(start, /soft: 0/, 'each lot must open with him asking for a full jump');
});

test('"going" is the close, and never sits on top of an ask he is about to cut', () => {
    // The complaint that started this: he said "going… GOING…" and then offered a SMALLER
    // increment, over and over. A warning he has no intention of keeping teaches the room to
    // ignore it. So the escalation is armed only on his last rung, where the next beat really is
    // "going once" — and the split is announced where it happens, at the start of the cheaper ask.
    const ticks = [...HTML.matchAll(/const stage = \(_[cv]Opening \|\| ([^)]*)\)/g)].map(m => m[1]);
    assert.equal(ticks.length, 2, 'both the phone and the TV countdowns must be found');
    for (const cond of ticks) assert.match(cond, /!last/, `"going…" is not held back to the last rung: ${cond}`);
    // and lastRung is what decides it, on the price the client can already see
    assert.ok(/function lastRung\(/.test(HTML), 'lastRung() decides when the close is next');
    for (const p of PRICES) {
        const n = RAISE.askLadderFor(p).length;
        assert.ok(!RAISE.lastRung(p, 0) || n === 1, `price ${p}: his opening ask is already his last`);
        assert.ok(RAISE.lastRung(p, n - 1), `price ${p}: the bottom rung is not the last`);
        assert.ok(RAISE.lastRung(p, 99), `price ${p}: past the bottom must still read as the last`);
    }
});

test('the fair warning carries no fresh ask, and the split is its own line', () => {
    const going = HTML.slice(HTML.indexOf('function sayGoing'), HTML.indexOf('function saySplit'));
    assert.ok(!/P_SPLIT/.test(going), 'the fair warning is still offering a discount in the same breath');
    assert.match(going, /P_GOING/, 'the fair warning must come from the fair-warning bank');
    // …and it is spoken at the moment he comes down, in BOTH handlers (the TV had no branch at
    // all, so the one beat the whole descent exists for used to pass in silence)
    for (const [from, to, who] of [['function applyMsg', 'function startClientGavel', 'the phone'],
                                   ['function applyViewerMsg', 'function startViewerGavel', 'the TV']]) {
        const src = HTML.slice(HTML.indexOf(from), HTML.indexOf(to));
        assert.match(src, /saySplit\(/, `${who} never announces that he has come down`);
    }
});

test('he does not chant a number he has already stopped asking for', () => {
    const src = HTML.slice(HTML.indexOf('function sayBid'), HTML.indexOf('function sayGoing'));
    assert.match(src, /softMinRaise\(msg\.bid\.price, msg\.bid\.soft/,
        'the two-number chant must name his CURRENT ask as the next price');
});

test('the voice is not a blur', () => {
    // Reported by ear: "incredibly rushed". Every number in this game is one somebody has to act
    // on, and a synthetic voice at 1.5× is not an auctioneer, it is noise. One dial for the whole
    // performance, and nothing may sit above a brisk conversational pace once it is applied.
    const dial = +HTML.match(/const SAY_RATE = ([\d.]+)/)[1];
    assert.ok(dial > 0 && dial <= 0.95, `SAY_RATE is ${dial} — that is not a slow-down`);
    assert.match(HTML, /u\.rate = \(opts\.rate \|\| [\d.]+\) \* SAY_RATE/, 'the dial must reach every utterance');
    const rates = [...HTML.matchAll(/rate: ([\d.]+)/g)].map(m => +m[1] * dial);
    assert.ok(rates.length >= 8, `only ${rates.length} spoken lines found`);
    for (const r of rates) assert.ok(r <= 1.12, `a line is spoken at ${r.toFixed(2)}× — still a blur`);
    // and the beats that WAIT for him to finish must follow the dial, or the banked board starts
    // the next round mid-sentence again
    assert.match(HTML, /const speechMs = [\s\S]{0,80}SAY_RATE/, 'speechMs must scale with SAY_RATE');
});

// ── the two message handlers must speak the same beats ──────────────────────
test('AUDIT: the phone speaks the same lines the TV does', () => {
    // The role gate was removed from canSpeak() so that any device may speak — but every say()
    // call lived in applyViewerMsg, the TV's handler. A phone runs applyMsg, so turning the voice
    // on there granted permission for something that was never invoked: the toggle did nothing
    // and there was no error to find. Neil hit exactly that.
    //
    // The two handlers are separate on purpose (a phone and a television show different things),
    // so this asserts only that neither loses a VOICE beat the other has.
    const slice = (from, to) => {
        const a = HTML.indexOf(from), b = HTML.indexOf(to, a);
        assert.ok(a >= 0 && b > a, `could not slice ${from}`);
        return HTML.slice(a, b);
    };
    const spoken = src => new Set([...src.matchAll(/\bsay([A-Z][a-zA-Z]*)\s*\(/g)].map(m => m[1]));

    // each handler plus the gavel ticker that belongs to it
    const tv = spoken(slice('function applyViewerMsg', 'function patchViewerBidding'));
    const phone = spoken(slice('function applyMsg', 'function sendBid'));

    const missingOnPhone = [...tv].filter(x => !phone.has(x));
    const missingOnTv = [...phone].filter(x => !tv.has(x));
    assert.deepEqual(missingOnPhone, [], `the TV says these and the phone does not: ${missingOnPhone}`);
    assert.deepEqual(missingOnTv, [], `the phone says these and the TV does not: ${missingOnTv}`);
    assert.ok(tv.size >= 6, `only ${tv.size} spoken beats found — has the slice drifted?`);
});

test('the voice is not gagged by the sound-effects toggle', () => {
    // They are two buttons. Having 🔊 also silence the auctioneer made "I turned the voice on and
    // nothing happened" a puzzle rather than a setting.
    const src = HTML.slice(HTML.indexOf('function canSpeak'), HTML.indexOf('function pickVoice'));
    assert.ok(/voiceOn\(\)/.test(src), 'canSpeak should consult the voice toggle');
    assert.ok(!/sfxOn/.test(src), 'canSpeak must not depend on sfxOn');
});

// ── which voice calls the auction ───────────────────────────────────────────
test('the best available voice wins, not the first one recognised', () => {
    // The old code took the first NAME it knew from a fixed list, so a machine holding both
    // Daniel and Google UK English Male got Daniel — the worse of the two — which is exactly
    // what was happening on Neil's laptop.
    assert.equal(best([
        { name: 'Daniel', lang: 'en-GB' },
        { name: 'Google UK English Male', lang: 'en-GB' },
        { name: 'Fred', lang: 'en-US' },
    ]), 'Google UK English Male');
});

test('a downloaded Premium or Enhanced voice is preferred automatically', () => {
    // Nobody should have to hard-code the name of whatever somebody installs through System
    // Settings — the bonus finds it.
    assert.equal(best([
        { name: 'Daniel', lang: 'en-GB' },
        { name: 'Daniel (Premium)', lang: 'en-GB' },
    ]), 'Daniel (Premium)');
    assert.equal(best([
        { name: 'Daniel', lang: 'en-GB' },
        { name: 'Daniel (Enhanced)', lang: 'en-GB' },
    ]), 'Daniel (Enhanced)');
    assert.equal(best([
        { name: 'Daniel (Enhanced)', lang: 'en-GB' },
        { name: 'Daniel (Premium)', lang: 'en-GB' },
    ]), 'Daniel (Premium)', 'Premium outranks Enhanced');
});

test('a name it knows beats a Premium voice it does not', () => {
    // Otherwise a premium NOVELTY voice — a Mac ships Bubbles, Zarvox and Trinoids — could
    // outrank a plain, sensible one.
    assert.equal(best([
        { name: 'Bubbles (Premium)', lang: 'en-US' },
        { name: 'Daniel', lang: 'en-GB' },
    ]), 'Daniel');
});

test('something is always chosen, even from an unrecognised list', () => {
    assert.equal(best([{ name: 'Zarvox', lang: 'en-US' }, { name: 'Whisper', lang: 'en-US' }]), 'Zarvox');
    assert.ok(VOICE.voiceScore({ name: 'anything', lang: 'en-GB' }) >= 0);
});

test('British edges it, all else equal', () => {
    assert.equal(best([
        { name: 'Unknownvoice', lang: 'en-US' },
        { name: 'Otherunknown', lang: 'en-GB' },
    ]), 'Otherunknown');
});

// ── the auctioneer's numbers ────────────────────────────────────────────────
test('anything over a thousand is spoken in THOUSANDS, never counted in hundreds', () => {
    // Twice reported by ear: "seventy hundred" for $7,000, then "thirty-one hundred" for $3,100.
    // Counting in hundreds is an American rostrum idiom and it was a bad fit here — but the
    // deciding argument is that the figure is on the screen at the same time, so the voice saying
    // anything other than "three thousand one hundred" reads as a mistake. This is the invariant:
    // above a thousand, the word "thousand" is always in there.
    for (let n = 1000; n <= 99000; n += 100) {
        const w = words(n);
        assert.ok(/thousand/.test(w), `${n} came out as "${w}" with no thousands in it`);
    }
});

test('the auctioneer says the number that is on the screen', () => {
    const cases = {
        42: 'forty-two', 15: 'fifteen', 90: 'ninety',
        190: 'one hundred and ninety', 700: 'seven hundred', 309: 'three hundred and nine',
        1000: 'one thousand', 1200: 'one thousand two hundred',
        3100: 'three thousand one hundred', 5900: 'five thousand nine hundred',
        7000: 'seven thousand', 10000: 'ten thousand',
        48000: 'forty-eight thousand', 67000: 'sixty-seven thousand',
        // the "and" belongs before a bare tail, and NOT once there are hundreds in it
        3022: 'three thousand and twenty-two', 2963: 'two thousand nine hundred and sixty-three',
        1005: 'one thousand and five', 40012: 'forty thousand and twelve',
        153309: 'one hundred and fifty-three thousand three hundred and nine',
    };
    for (const [n, want] of Object.entries(cases)) {
        assert.equal(words(+n), want, `${n} should be "${want}"`);
    }
});

test('every number the ask ladder can produce is speakable', () => {
    // The real guard: sweep the actual asks for the actual lots and insist nothing comes out
    // malformed — no empty words, no "undefined", and never a hundreds-count above ninety-nine.
    const seen = new Set();
    for (const lot of LOTS) for (let i = 0; i < 6; i++) ASK.askLadder(lot.value).forEach(a => seen.add(a));
    // roundAsk collapses everything to two significant figures, so a thousand lots yield a few
    // hundred distinct calls, not a few thousand. This only guards against the sweep going empty.
    assert.ok(seen.size > 250, `only ${seen.size} distinct asks swept`);
    for (const a of seen) {
        const w = words(a);
        assert.ok(w && !/undefined|NaN/.test(w), `${a} spoke as "${w}"`);
        assert.ok(!/hundred hundred/.test(w), `${a} spoke as "${w}"`);
        // the invariant from the test above, applied to every ask the game can actually call
        if (a >= 1000) assert.ok(/thousand|million/.test(w), `${a} spoke as "${w}"`);
        if (a < 1000) assert.ok(!/thousand/.test(w), `${a} spoke as "${w}"`);
    }
});

test('lot count scales with the table, ~3 per player', () => {
    // "Everyone goes home with about three things" should hold at any table size.
    for (const players of [2, 4, 6, 10]) {
        const { plannedLotCount } = makeDraw({ lotsPer: 3, bigLot: false }, players);
        assert.equal(plannedLotCount(), players * 3, `${players} players should draw ${players * 3} lots`);
    }
    const { plannedLotCount } = makeDraw({ lotsPer: 2, bigLot: false }, 6);
    assert.equal(plannedLotCount(), 12, 'the Short setting should be 2 lots per player');
});
