// Unit tests for Going, Going, GONE!'s lot data and draw — `npm run test:unit`, no browser.
//
// The lots are REAL items with researched prices, and the JSON files are the source of truth;
// goinggone.html carries an embedded copy generated by scripts/build-goinggone-lots.js. The most
// valuable test here is the first one: it fails when somebody edits the JSON and forgets to
// regenerate, which would otherwise show up as a wrong price mid-game with no error anywhere.
//
// The second most valuable is the BAND DEPTH suite. Lots are dealt evenly across four price
// bands, so a band with too few researched lots silently starts repeating items within a single
// auction. That is a research gap, not a code bug, and this is where it surfaces.
const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const HTML = fs.readFileSync(path.join(ROOT, 'goinggone.html'), 'utf8');

// ── pull the embedded lots and the draw out of the page ─────────────────────
const LOTS = new Function(HTML.match(/const LOTS = \[[\s\S]*?\n\];/)[0] + '\nreturn LOTS;')();

const DRAW_SRC = (() => {
    const a = HTML.indexOf('const TIERS = [');
    const b = HTML.indexOf('function hostStartAuction', a);
    assert.ok(a >= 0 && b > a, 'could not slice the lot-draw block out of goinggone.html');
    return HTML.slice(a, b);
})();

// The auctioneer's ask ladder + reserve live up with the raise ladder, not with the draw.
const ASK_SRC = (() => {
    const a = HTML.indexOf('const RESERVE_FRAC =');
    const b = HTML.indexOf('const PLAYER_COLORS', a);
    assert.ok(a >= 0 && b > a, 'could not slice the ask-ladder block out of goinggone.html');
    return HTML.slice(a, b);
})();

// Evaluate the draw with its collaborators passed in as parameters, so nothing touches globals.
// `ceiling` is the richest bankroll — Infinity in most tests, where affordability is not the point.
const makeDraw = (settings, players = 6) => {
    const shuffle = a => a.slice();                     // deterministic: identity shuffle
    const H = { settings, mysteryLots: null, usedLots: null };
    const fn = new Function('LOTS', 'shuffle', 'H', 'MIN_PLAYERS', 'connectedPlayers', 'reserveFor',
        DRAW_SRC + '\nreturn { buildLotOrder, plannedLotCount, roundBands, TIERS, BAND_SPAN, OVER_BAND, REACH, MYSTERY_SHARE, H };');
    const d = fn(LOTS, shuffle, H, 2, () => Array.from({ length: players }), v => Math.round(v * 0.25));
    // most tests predate rounds and just want "one round, everything affordable"
    const raw = d.buildLotOrder;
    d.buildLotOrder = (n, round = 1, rounds = 1, ceiling = Infinity) => raw(n, round, rounds, ceiling);
    d.rawBuildLotOrder = raw;
    return d;
};

const ASK = new Function(ASK_SRC + '\nreturn { askLadder, reserveFor, roundAsk, RESERVE_FRAC, ASK_HI, ASK_LO, ASK_STEPS };')();

// The auctioneer speaks his numbers, so they have to be built into words rather than left to a
// speech engine to spell out digit by digit.
const SPEAK_SRC = (() => {
    const a = HTML.indexOf('const ONES = [');
    const b = HTML.indexOf('const pick = ', a);
    assert.ok(a >= 0 && b > a, 'could not slice the number-to-words block out of goinggone.html');
    return HTML.slice(a, b);
})();
const { words } = new Function(SPEAK_SRC + '\nreturn { words };')();

const SOURCES = ['data/goinggone-lots-real.json', 'data/goinggone-lots-catalogue.json'];
const jsonLots = SOURCES
    .flatMap(f => JSON.parse(fs.readFileSync(path.join(ROOT, f), 'utf8')).lots)
    .filter(l => Math.round(l.value) > 0);

// ── the embed matches its source ────────────────────────────────────────────
test('embedded LOTS matches the JSON sources — run scripts/build-goinggone-lots.js if this fails', () => {
    assert.equal(LOTS.length, jsonLots.length,
        `embed has ${LOTS.length} lots, JSON has ${jsonLots.length} — the embed is stale`);
    jsonLots.forEach((src, i) => {
        assert.equal(LOTS[i].name, src.name, `lot ${i} name drifted from the JSON`);
        assert.equal(LOTS[i].value, Math.round(src.value), `lot ${i} (${src.name}) value drifted`);
    });
});

test('every value is a positive whole number of dollars', () => {
    // The game's coin arithmetic is integer and bidding in cents is silly, so the build script
    // rounds. A stray float here would show up as $4084.85 on a lot card.
    for (const l of LOTS) {
        assert.ok(Number.isInteger(l.value), `${l.name} has a non-integer value ${l.value}`);
        assert.ok(l.value > 0, `${l.name} is worth ${l.value} — nothing free or negative`);
    }
});

test('every lot carries the provenance shown while bidding', () => {
    // src + capture date are rendered on the lot card on purpose: real prices move, and a
    // figure that looks wrong needs a visible explanation rather than looking like a bug.
    for (const l of LOTS) {
        assert.ok(l.src && l.src.length, `${l.name} has no source label`);
        assert.match(l.on || '', /^\d{4}-\d{2}-\d{2}$/, `${l.name} has no capture date`);
    }
});

// ── no lot may reveal its own price ─────────────────────────────────────────
// The whole game is guessing what the thing costs. The catalogue harvest wrote the price into
// the flavour text ("A lump of iron with a handle. Thirty-eight dollars.") — 57 lots leaked
// their own answer onto the bidding screen before this test existed. Checks the JSON sources,
// not the embed, so the failure names the file to fix.
const NUM_WORD = '(?:one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|' +
    'fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty|sixty|' +
    'seventy|eighty|ninety|hundred|thousand|million)';
const PRICE_LEAKS = [
    /\$\s*\d/,                                      // "$799"
    /\b(?:dollars?|cents?|bucks|quid)\b/i,          // "…dollars." / "Fifty cents." spelled out or not
    new RegExp('\\b(?:' + NUM_WORD + '|\\d+)[\\s-]*grand\\b', 'i'),  // "four grand", "10 grand"
    // Comparative hints are banned too — "costs more than a car", "the most expensive harp
    // there is", "twice the price". Fuzzier than a number, but still the auctioneer whispering
    // the answer. Any price-adjacent word fails; reword the joke around it.
    /\b(?:price[sdy]?|priciest|cost(?:s|ing|ly)?|cheap(?:er|est)?|expensive|afford(?:able)?|bargain|fortune|worth)\b/i,
];
test('no lot name or description states its own price', () => {
    const leaks = [];
    for (const f of SOURCES) {
        for (const l of JSON.parse(fs.readFileSync(path.join(ROOT, f), 'utf8')).lots) {
            for (const field of ['name', 'desc']) {
                const hit = PRICE_LEAKS.find(re => re.test(l[field] || ''));
                if (hit) leaks.push(`${f}: "${l.name}" ${field} leaks the price (${hit}): ${l[field]}`);
            }
        }
    }
    assert.deepEqual(leaks, [],
        `${leaks.length} lot(s) reveal their price on the bidding screen:\n  ` + leaks.join('\n  '));
});

// ── band depth: a research check, not a code check ──────────────────────────
// Repeats are impossible by construction now (H.usedLots excludes everything already dealt, in
// this round and every earlier one), so a thin tier no longer shows the same item twice. What it
// does instead is quietly under-represent itself: the draw rotates on to the next tier and the
// round loses the price range it was supposed to span. So the hard floor is "deep enough for an
// ordinary table", and anything thinner than the largest possible draw is REPORTED as a research
// target rather than failed — the top tier is only ever reached in the last round of a 3-round
// game, and holding the whole suite red over it would be dishonest about the severity.
test('every price tier is deep enough for an ordinary table', () => {
    const { TIERS, BAND_SPAN } = makeDraw({ lotsPer: 3, bigLot: false });
    const TYPICAL = 6 * 3;                               // 6 players, the Normal setting
    const MAX_DRAW = 10 * 4;                             // MAX_PLAYERS x the longest setting
    const floor = Math.ceil(TYPICAL / BAND_SPAN);
    const want = Math.ceil(MAX_DRAW / BAND_SPAN);
    const report = [], thin = [];
    for (const [lo, hi] of TIERS) {
        const n = LOTS.filter(l => l.value >= lo && l.value < hi).length;
        report.push(`$${lo}-${hi}: ${n}`);
        if (n < want) thin.push(`$${lo}-${hi} has ${n}, wants ${want} for the biggest table`);
        assert.ok(n >= floor,
            `tier $${lo}-${hi} has only ${n} lots and an ordinary table draws ${floor} — ` +
            `research more lots in this tier or a round stops spanning its price range`);
    }
    console.log('      tier depth →', report.join(', '));
    if (thin.length) console.log('      RESEARCH TARGETS →', thin.join('; '));
});

// ── the draw ────────────────────────────────────────────────────────────────
test('buildLotOrder returns the requested number of DISTINCT lots', () => {
    const { buildLotOrder } = makeDraw({ lotsPer: 3, bigLot: false });
    for (const count of [6, 12, 18, 30, 40]) {
        const order = buildLotOrder(count);
        assert.equal(order.length, count, `asked for ${count} lots, got ${order.length}`);
        assert.equal(new Set(order).size, count, `count ${count} repeated a lot within one auction`);
    }
});

test('the draw spreads evenly across the bands', () => {
    // This is what makes a short auction still span $1 to $10,000 instead of clumping, and it is
    // the assumption every balance figure in goinggoneplan-realitems.md rests on.
    const { buildLotOrder, roundBands } = makeDraw({ lotsPer: 3, bigLot: false });
    const order = buildLotOrder(20);
    const counts = roundBands(1, 1).map(([lo, hi]) => order.filter(i => LOTS[i].value >= lo && LOTS[i].value < hi).length);
    assert.deepEqual(counts, [5, 5, 5, 5], `expected an even spread, got ${counts.join('/')}`);
});

test('over-band lots stay out unless the captain asks for one', () => {
    // The simulator is unambiguous: one lot worth more than the whole ordinary band takes the
    // winner's margin from ~10% of their score to ~48%, i.e. it decides the game by itself.
    const off = makeDraw({ lotsPer: 3, bigLot: false });
    const offOrder = off.buildLotOrder(18);
    assert.equal(offOrder.filter(i => LOTS[i].value >= off.OVER_BAND).length, 0,
        'a big lot appeared with the setting off — that silently changes the balance of every game');

    const on = makeDraw({ lotsPer: 3, bigLot: true });
    const onOrder = on.buildLotOrder(18);
    assert.equal(onOrder.filter(i => LOTS[i].value >= on.OVER_BAND).length, 1,
        'bigLot should add exactly one over-band lot, never more');
});

test('mystery lots always have a photo, because the photo is all you get', () => {
    // A mystery lot withholds the name and shows the picture. One without a picture would be a
    // blank card nobody can bid on sensibly.
    const draw = makeDraw({ lotsPer: 3, bigLot: false });
    const order = draw.buildLotOrder(20);
    const mystery = [...draw.H.mysteryLots];
    assert.ok(mystery.length > 0, 'no mystery lots were chosen at all');
    assert.equal(mystery.length, Math.round(order.length * draw.MYSTERY_SHARE));
    for (const i of mystery) {
        assert.ok(LOTS[i].img, `${LOTS[i].name} was made a mystery lot but has no photo`);
        assert.ok(order.includes(i), 'a mystery lot was chosen that is not even in this auction');
    }
});

// ── rounds: the bands climb, and nothing is ever sold twice ─────────────────
test('the band window climbs with the round and always tops out in the last one', () => {
    const { roundBands, TIERS, BAND_SPAN } = makeDraw({ lotsPer: 3, bigLot: false });
    // one round: the ordinary spread, never the monsters
    assert.deepEqual(roundBands(1, 1), TIERS.slice(0, BAND_SPAN));
    // three rounds: opens ordinary, ends at the top of the ladder
    assert.deepEqual(roundBands(1, 3), TIERS.slice(0, BAND_SPAN));
    assert.deepEqual(roundBands(3, 3), TIERS.slice(-BAND_SPAN));
    // two rounds must ALSO reach the top by the end — a shorter game should not be capped out of
    // the private-aircraft tier just for being shorter
    assert.deepEqual(roundBands(2, 2), TIERS.slice(-BAND_SPAN));
    // and the window never falls off the end of the ladder
    for (const rounds of [1, 2, 3]) {
        for (let r = 1; r <= rounds; r++) {
            assert.equal(roundBands(r, rounds).length, BAND_SPAN, `round ${r}/${rounds} lost a tier`);
        }
    }
});

test('a multi-round game never sells the same item twice', () => {
    // H.usedLots spans the whole game, not the round. Without it round 3 can re-deal round 1's
    // lot — and a player who watched it get valued knows exactly what it is worth.
    const draw = makeDraw({ lotsPer: 3, bigLot: false });
    const seen = new Set();
    for (let round = 1; round <= 3; round++) {
        const order = draw.buildLotOrder(18, round, 3, Infinity);
        for (const i of order) {
            assert.ok(!seen.has(i), `${LOTS[i].name} was dealt twice in one game (round ${round})`);
            seen.add(i);
        }
    }
});

test('a lot nobody could clear the reserve on never reaches the running order', () => {
    // Affordability is judged lot by lot: a $70,000 oven in front of a table holding $9,000 is a
    // pass-in nobody enjoyed. REACH is how much of the richest bankroll a reserve may demand.
    const draw = makeDraw({ lotsPer: 3, bigLot: false });
    const ceiling = 9000;
    const order = draw.buildLotOrder(18, 3, 3, ceiling);
    for (const i of order) {
        assert.ok(ASK.reserveFor(LOTS[i].value) <= ceiling * draw.REACH,
            `${LOTS[i].name} ($${LOTS[i].value}) was dealt to a table whose richest player holds $${ceiling}`);
    }
});

// ── the auctioneer's ask ────────────────────────────────────────────────────
test('the ask ladder descends, and never goes under the reserve', () => {
    // The floor is the whole point: below it the lot is passed in rather than given away.
    for (const value of [1, 15, 99, 450, 2200, 9500, 19799, 70886]) {
        for (let n = 0; n < 200; n++) {
            const ladder = ASK.askLadder(value);
            assert.ok(ladder.length >= 1 && ladder.length <= ASK.ASK_STEPS, `${value}: ${ladder.length} rungs`);
            ladder.forEach((a, i) => {
                assert.ok(a >= ASK.reserveFor(value) || a >= value * ASK.RESERVE_FRAC,
                    `${value}: rung ${a} is under the reserve ${ASK.reserveFor(value)}`);
                assert.ok(a >= 1, `${value}: rung ${a} is not a price`);
                if (i) assert.ok(a < ladder[i - 1], `${value}: ladder went UP (${ladder.join(' → ')})`);
            });
            // +1 of slack: rounding a $1 tulip bulb to a callable number can only go up
            assert.ok(ladder[0] <= Math.max(1, value * ASK.ASK_HI) * 1.05 + 1,
                `${value}: opening ask ${ladder[0]} is beyond even a dishonest auctioneer`);
        }
    }
});

test('the opening ask is sometimes a gift and sometimes a swindle', () => {
    // If he always asked above the value the room would learn to wait every time, and if he always
    // asked below it there would be no risk in jumping early. Both sides must actually occur.
    const value = 4000;
    let over = 0, under = 0;
    for (let n = 0; n < 400; n++) {
        const open = ASK.askLadder(value)[0];
        if (open > value) over++; else under++;
    }
    assert.ok(over > 20 && under > 20, `openings were one-sided: ${over} over / ${under} under`);
});

test('asks are round numbers a person would say out loud', () => {
    // "Who will start me at forty-seven thousand three hundred and eighteen?" — no.
    for (const v of [850, 4200, 19799, 70886]) {
        for (const a of ASK.askLadder(v)) {
            const digits = String(a).replace(/0+$/, '').length;
            assert.ok(a < 20 || digits <= 2, `${a} is not a number an auctioneer would call`);
        }
    }
});

// ── the auctioneer's numbers ────────────────────────────────────────────────
test('anything over a thousand is spoken in THOUSANDS, never counted in hundreds', () => {
    // Twice reported by ear: "seventy hundred" for $7,000, then "thirty-one hundred" for $3,100.
    // Counting in hundreds is an American rostrum idiom and it was a bad fit here — but the
    // deciding argument is that the figure is on the screen at the same time, so the voice saying
    // anything other than "three thousand one hundred" reads as a mistake. This is the invariant:
    // above a thousand, the word "thousand" is always in there.
    for (let n = 1000; n <= 99000; n += 100) {
        const w = words(n);
        assert.ok(/thousand/.test(w), `${n} came out as "${w}" with no thousands in it`);
    }
});

test('the auctioneer says the number that is on the screen', () => {
    const cases = {
        42: 'forty-two', 15: 'fifteen', 90: 'ninety',
        190: 'one hundred and ninety', 700: 'seven hundred', 309: 'three hundred and nine',
        1000: 'one thousand', 1200: 'one thousand two hundred',
        3100: 'three thousand one hundred', 5900: 'five thousand nine hundred',
        7000: 'seven thousand', 10000: 'ten thousand',
        48000: 'forty-eight thousand', 67000: 'sixty-seven thousand',
        153309: 'one hundred and fifty-three thousand three hundred and nine',
    };
    for (const [n, want] of Object.entries(cases)) {
        assert.equal(words(+n), want, `${n} should be "${want}"`);
    }
});

test('every number the ask ladder can produce is speakable', () => {
    // The real guard: sweep the actual asks for the actual lots and insist nothing comes out
    // malformed — no empty words, no "undefined", and never a hundreds-count above ninety-nine.
    const seen = new Set();
    for (const lot of LOTS) for (let i = 0; i < 6; i++) ASK.askLadder(lot.value).forEach(a => seen.add(a));
    // roundAsk collapses everything to two significant figures, so a thousand lots yield a few
    // hundred distinct calls, not a few thousand. This only guards against the sweep going empty.
    assert.ok(seen.size > 250, `only ${seen.size} distinct asks swept`);
    for (const a of seen) {
        const w = words(a);
        assert.ok(w && !/undefined|NaN/.test(w), `${a} spoke as "${w}"`);
        assert.ok(!/hundred hundred/.test(w), `${a} spoke as "${w}"`);
        // the invariant from the test above, applied to every ask the game can actually call
        if (a >= 1000) assert.ok(/thousand|million/.test(w), `${a} spoke as "${w}"`);
        if (a < 1000) assert.ok(!/thousand/.test(w), `${a} spoke as "${w}"`);
    }
});

test('lot count scales with the table, ~3 per player', () => {
    // "Everyone goes home with about three things" should hold at any table size.
    for (const players of [2, 4, 6, 10]) {
        const { plannedLotCount } = makeDraw({ lotsPer: 3, bigLot: false }, players);
        assert.equal(plannedLotCount(), players * 3, `${players} players should draw ${players * 3} lots`);
    }
    const { plannedLotCount } = makeDraw({ lotsPer: 2, bigLot: false }, 6);
    assert.equal(plannedLotCount(), 12, 'the Short setting should be 2 lots per player');
});
